name: Acceptance Tests

on:
  workflow_call:

jobs:
  test:
    name: 'Acceptance Tests (OS: ${{ matrix.os }} / TF: ${{ matrix.terraform }})'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-latest
          # - windows-latest
          - ubuntu-latest
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - '1.3.*'
          - '1.4.*'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version-file: 'go.mod'
    - name: Setup Terraform ${{ matrix.terraform }}
      uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false
    - name: Run acceptance tests
      run: make testacc | tee test_result.txt
      shell: bash
      env:
        ACCTEST_PARALLELISM: 10
        BASTIONZERO_API_SECRET: ${{ secrets.ACCEPTANCE_TESTS_API_SECRET }}
        BASTIONZERO_HOST: ${{ secrets.ACCEPTANCE_TESTS_BASTIONZERO_HOST }}
    - name: Check that no test is skipped
      run: >-
        grep "SKIP" test_result.txt -B 2;
        retVal=$?;
        if [ $retVal -ne 1 ]; then
          echo "*** Some tests were skipped. Please ensure that no tests are skipped by creating the respective API objects listed above.";
          exit 1;
        else
          echo "*** No tests were skipped!";
          exit 0;
        fi
      shell: bash {0} # override -e default