name: Sweep Leftover Resources

# Warning: Be careful not to run this when there are in-progress acceptance
# tests
on:
  workflow_dispatch:

jobs:
  sweep-now:
    uses: ./.github/workflows/sweep.yml
    secrets: inherit