name: Sweep Leftover Resources

on:
  # Warning: Be careful not to run this when there are in-progress acceptance
  # tests
  workflow_dispatch:
  # Sweep leftover resources on Saturday night when it is less likely for there
  # to be an in-progress acceptance test
  schedule:
    - cron: 0 0 * * SAT # Every Saturday at 00:00 UTC

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
      - name: Sweep leftover resources
        run: make sweep
        env:
          BASTIONZERO_API_SECRET: ${{ secrets.ACCEPTANCE_TESTS_API_SECRET }}
          BASTIONZERO_HOST: ${{ vars.ACCEPTANCE_TESTS_BASTIONZERO_HOST }}