name: Unit Tests

# Runs unit tests for pull requests and pushes to master.
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: make vet
      - name: Test
        run: make test