name: Unit Tests

# Runs unit tests for pull requests and pushes to master.
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: make vet
      - name: Test
        run: make test